run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

issues:
  exclude-dirs:
    - npm
